"""Add companion columns

Revision ID: 06584da94791
Revises: 5c0a91acb6fa
Create Date: 2025-08-24 13:28:21.786833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06584da94791'
down_revision = '5c0a91acb6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companion_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('companion_machine_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('companion_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('companion_last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('companion_status', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_companion_token', ['companion_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_companion_token', type_='unique')
        batch_op.drop_column('companion_status')
        batch_op.drop_column('companion_last_seen')
        batch_op.drop_column('companion_version')
        batch_op.drop_column('companion_machine_id')
        batch_op.drop_column('companion_token')

    # ### end Alembic commands ###