"""add sound_volume column

Revision ID: 3139734bb73e
Revises: e8d211fb2567
Create Date: 2025-08-19 13:09:50.349347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3139734bb73e'
down_revision = 'e8d211fb2567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sound_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('system_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('connection_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('milestone_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rare_achievement_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_quiet_hours_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('notification_quiet_hours_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_quiet_hours_end')
        batch_op.drop_column('notification_quiet_hours_start')
        batch_op.drop_column('rare_achievement_notifications_enabled')
        batch_op.drop_column('milestone_notifications_enabled')
        batch_op.drop_column('connection_notifications_enabled')
        batch_op.drop_column('error_notifications_enabled')
        batch_op.drop_column('sync_notifications_enabled')
        batch_op.drop_column('system_notifications_enabled')
        batch_op.drop_column('sound_volume')

    # ### end Alembic commands ###
