"""Increase password_hash column size

Revision ID: 3b588297a429
Revises: b49d18836868
Create Date: 2025-12-12 13:01:40.188196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b588297a429'
down_revision = 'b49d18836868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.String(length=128),
                              type_=sa.String(length=256),
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.String(length=256),
                              type_=sa.String(length=128),
                              existing_nullable=True)
    # ### end Alembic commands ###