"""Add last_synced field to Game model

Revision ID: 5c0a91acb6fa
Revises: 3139734bb73e
Create Date: 2025-08-20 12:45:24.056867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0a91acb6fa'
down_revision = '3139734bb73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('last_synced')

    # ### end Alembic commands ###
