"""Add notification preferences (always enabled)

Revision ID: ab8c10927484
Revises: eb9a1f7a5463
Create Date: 2025-11-22 14:56:49.785347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8c10927484'
down_revision = 'eb9a1f7a5463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sound_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trophy_popup_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trophy_popup_enabled')
        batch_op.drop_column('sound_enabled')
        batch_op.drop_column('notification_enabled')

    # ### end Alembic commands ###
