"""Remove user preference fields

Revision ID: b49d18836868
Revises: ab8c10927484
Create Date: 2025-11-25 15:12:27.744364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49d18836868'
down_revision = 'ab8c10927484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('sound_file')
        batch_op.drop_column('sound_enabled')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trophy_popup_enabled')
        batch_op.drop_column('sound_enabled')
        batch_op.drop_column('notification_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sound_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('trophy_popup_enabled', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sound_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sound_file', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
