"""Remove sound preference fields from User model

Revision ID: eb9a1f7a5463
Revises: 06584da94791
Create Date: 2025-11-18 13:06:41.401001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9a1f7a5463'
down_revision = '06584da94791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sync_notifications_enabled')
        batch_op.drop_column('system_notifications_enabled')
        batch_op.drop_column('sound_enabled')
        batch_op.drop_column('trophy_popup_enabled')
        batch_op.drop_column('notification_quiet_hours_start')
        batch_op.drop_column('trophy_style')
        batch_op.drop_column('connection_notifications_enabled')
        batch_op.drop_column('rare_achievement_notifications_enabled')
        batch_op.drop_column('notification_enabled')
        batch_op.drop_column('sound_volume')
        batch_op.drop_column('notification_quiet_hours_end')
        batch_op.drop_column('notification_sound_pack')
        batch_op.drop_column('error_notifications_enabled')
        batch_op.drop_column('milestone_notifications_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('error_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('notification_sound_pack', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('notification_quiet_hours_end', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('sound_volume', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('notification_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('rare_achievement_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('connection_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('trophy_style', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('notification_quiet_hours_start', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('trophy_popup_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sound_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('system_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sync_notifications_enabled', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
